[discovery]
    endpoints = ["127.0.0.1:2379"]

[grpcserver]
    appId            = ["echo"]
    logPath          = "./log"
    logStdout        = true
    errorLogEnabled  = true
    accessLogEnabled = true

