registry:
  endpoints: ["127.0.0.1:2379"]

grpcserver:
  name:            "demo"
  logPath:          "./log"
  logStdout:        true
  errorLogEnabled:  true
  accessLogEnabled: true
  errorStack:       true

